# syntax=docker/dockerfile:1

# Stage 1: build-time preparation
# Clone upstream repos, download binaries, extract scripts, strip .git dirs
FROM registry.access.redhat.com/hi/core-runtime:latest-builder AS builder

# renovate: datasource=github-releases depName=pi-hole/FTL
ARG FTL_VERSION=v6.6.2
# renovate: datasource=github-releases depName=pi-hole/pi-hole
ARG PIHOLE_CORE_VERSION=v6.4.2
# renovate: datasource=github-releases depName=pi-hole/web
ARG PIHOLE_WEB_VERSION=v6.5.1

RUN dnf install -y \
    --setopt=install_weak_deps=False \
    --setopt=tsflags=nodocs \
    binutils \
    curl \
    git \
    && dnf clean all

RUN git clone --branch ${PIHOLE_CORE_VERSION} --single-branch --depth 1 \
    https://github.com/pi-hole/pi-hole.git /etc/.pihole \
    && git clone --branch ${PIHOLE_WEB_VERSION} --single-branch --depth 1 \
    https://github.com/pi-hole/web.git /var/www/html/admin \
    && rm -rf /etc/.pihole/.git /var/www/html/admin/.git

RUN cd /etc/.pihole && \
    install -Dm755 -d /opt/pihole && \
    install -Dm755 -t /opt/pihole gravity.sh && \
    install -Dm755 -t /opt/pihole ./advanced/Scripts/*.sh && \
    install -Dm755 -t /opt/pihole ./advanced/Scripts/COL_TABLE && \
    install -Dm755 -d /etc/pihole && \
    install -Dm644 -t /etc/pihole ./advanced/Templates/logrotate && \
    install -Dm755 -t /usr/local/bin pihole && \
    install -Dm644 ./advanced/bash-completion/pihole.bash /etc/bash_completion.d/pihole && \
    install -Dm644 ./advanced/bash-completion/pihole-ftl.bash /etc/bash_completion.d/pihole-FTL && \
    install -T -m 0755 ./advanced/Templates/pihole-FTL-poststop.sh /opt/pihole/pihole-FTL-poststop.sh

ADD https://ftl.pi-hole.net/macvendor.db /macvendor.db

RUN curl -sSL \
    "https://github.com/pi-hole/ftl/releases/download/${FTL_VERSION}/pihole-FTL-amd64" \
    -o /usr/bin/pihole-FTL \
    && chmod +x /usr/bin/pihole-FTL \
    && readelf -h /usr/bin/pihole-FTL || (echo "Error with FTL binary" && exit 1)

# Stage 2: runtime image
FROM registry.access.redhat.com/hi/core-runtime@sha256:9c7c8552fee26f6ae292e5f959a1987ab141f6bad69be0e3063686c86dbaf1a4

USER root

ENV DNSMASQ_USER=pihole
ENV FTL_CMD=no-daemon

RUN --mount=type=bind,from=registry.access.redhat.com/hi/core-runtime:latest-builder,target=/builder \
    LD_LIBRARY_PATH=/builder/lib64:/builder/usr/lib64 \
    RPM_CONFIGDIR=/builder/usr/lib/rpm \
    /builder/usr/bin/dnf install -y \
    --installroot=/ \
    --setopt=reposdir=/builder/etc/yum.repos.d \
    --setopt=install_weak_deps=False \
    --setopt=tsflags=nodocs \
    bind-utils \
    busybox \
    iproute \
    logrotate \
    procps-ng \
    psmisc \
    tzdata

RUN echo "pihole:x:1000:1000:Pi-hole:/:/sbin/nologin" >> /etc/passwd \
    && echo "pihole:x:1000:" >> /etc/group

COPY --from=builder /usr/bin/pihole-FTL /usr/bin/pihole-FTL
COPY --from=builder /macvendor.db /macvendor.db
COPY --from=builder /etc/.pihole/ /etc/.pihole/
COPY --from=builder /var/www/html/admin/ /var/www/html/admin/
COPY --from=builder /opt/pihole/ /opt/pihole/
COPY --from=builder /usr/local/bin/pihole /usr/local/bin/pihole
COPY --from=builder /etc/bash_completion.d/ /etc/bash_completion.d/
COPY --from=builder /etc/pihole/logrotate /etc/pihole/logrotate

RUN install -Dm755 -d /var/log/pihole \
    && install -Dm755 -d /var/lib/logrotate

COPY --chmod=0755 bash_functions.sh /usr/bin/bash_functions.sh
COPY --chmod=0755 prefix-time.sh /usr/bin/prefix-time.sh
COPY --chmod=0755 start.sh /usr/bin/start.sh
COPY --chmod=0755 pihole-FTL-prestart.sh /opt/pihole/pihole-FTL-prestart.sh
COPY crontab.txt /crontab.txt

EXPOSE 53 53/udp
EXPOSE 80

HEALTHCHECK CMD dig -p $(pihole-FTL --config dns.port) +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1

ENTRYPOINT ["start.sh"]
